name: SuperVanish-V2
main: ErkamKahriman\Vanish\Vanish
version: 2.0.0
author: ErkamKahriman
api: 3.0.0-ALPHA11
commands:
  supervanish:
    description: "Vanish yourself"
permissions:
  supervanish.spectate:
    description: "Vanish use permission"
    default: op
